@echo off
echo Checking for processes on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000') do (
    echo Killing process %%a on port 3000...
    taskkill /F /PID %%a >nul 2>&1
)
echo Starting Medhal development server...
npm run dev
